### ISSUE TITLE
Enhancements : stdin, csv format and runbook_url

### ISSUE THREAD

**Issue by tpoindessous** [plexsystems/promdoc#1]
Hi ! 

I would like to propose several enhancements :) 

- stdin : I use kustomize and I would like to pipe it to promdoc, without having a temporary file.
- csv format: I would like to use your output and put i in a Google Sheet document, so I think I need a CSV format ...
- runbook_url : it would be very nice to have another column for runbook_url. If you want to handle a dynamic config for columns, why not :) :) :) 

I will try to submit you a PR and my coworker @nlamirault will also look at these ;)

thanks for your work !

Have a nice day.

Thomas

**Comment by jpreese** [comment]
@tpoindessous all of those features would be most welcome. I am looking forward to your contribution! 😄

**Comment by tpoindessous** [comment]
For CSV, since markdown use | as separator, it should work !

**Comment by jpreese** [comment]
A CSV output is definitely doable. You might have better success if you wrote a new method that just handled formatting the `[]RuleGroup` as CSV. 

Right now there's just `getDocumentation` that renders Markdown. I could see us writing `renderMarkdown()`, `renderCSV()`, `renderJSON()`, etc methods that supported a number of outputs. We could control this with a flag on the CLI to say what format to output (e.g. `generate -o CSV`)

I wouldn't worry about trying to convert Markdown to CSV!

**Comment by jpreese** [comment]
@tpoindessous this has been released in `0.3.0`. Please let me know if that satisfies your use case or if we need to make any changes. Thanks again for your contribution!
