### ISSUE TITLE
Change output path to a flag

### ISSUE THREAD

**Issue by jpreese** [plexsystems/promdoc#7]
The current behavior is to pass in the `output-dir` as a parameter when calling the `generate` command. i.e.

```shell
promdoc generate <output-dir>
```

The output should be set as an `--out` flag. 

1. If `--out` is **not** is set, the default should be creating `alerts.md` in the current working directory.
2. If `--out` is set, the file should be generated to the location specified.
    - NOTE: If `out` is a directory, the result should be creating `alerts.md` in that directory, otherwise the location as it appears.

**Comment by Zelinzky** [comment]
Working on this. @jpreese When running [rendering.Render](https://github.com/plexsystems/promdoc/blob/1f95d42093dd7ec57b34750dafb292692bd59394/internal/commands/generate.go#L46) is the workingDir different to the output dir?

**Comment by jpreese** [comment]
Resolved via #8
